### ISSUE TITLE
Support SSR 

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icejs#7]
### 工程配置

在 build.json 配置 ssr 为 true

```diff
{
+ "ssr": true, 
}
```

### 应用数据

```diff
import { createApp } from 'ice';
createApp({
 app: {
   // 获取初始数据
+   getInitialProps: async () => {
+    return {};
+   }
 }
});
```

### 数据请求

在 SSR 应用中，推荐在页面入口组件中定义 getInitialProps 属性，来处理数据请求的工作：

```diff
import React from 'react'
import { request } from 'ice'

const Home = ({ stars }) => {
  return <div>{stars}</div>
};

+Home.getInitialProps = async () => {
+  const res = await request('https://api.github.com/repos/ice-lab/icejs')
+  const json = await res.json()
+  return { stars: json.stargazers_count };
+};

Home.pageConfig = {
  // SSR 支持的配置项：详见底部讨论区
+  title: 'Home Page',
}

export default Home;
```

- 通过 `getInitialProps`  返回的数据，将被作为组件的初始 props
- 在 server 端， `getInitalProps`  会在页面 render 之前被执行，其返回值将作为页面的初始 props 用于渲染。同时这份数据会被放置于页面中
- 在 client 端，会优先去检测页面中是否输出了这份数据，如果有，则使用这份数据 hydrate 页面，如果没有，则执行 `getInitialProps` 
- 只有放在 pages 目录下的路由组件，它的 `getInitialProps`  才会被调用，子组件使用 `getInitialProps`  是无效的

### 构建产物
```
.
├── build
│   ├── index.html
│   ├── css/index.css
│   ├── js/index.js
│   └── server.js
```

### 核心点

- 一套路由：统一前端路由与服务端路由
- 数据请求：支持切换路由时自动获取数据
- HTML 模板：支持配置 HTML 模板

### 一套路由

客户端和服务端使用一套路由，服务端通过 `ctx.path`  查找请求对应的组件。封装 `getComponentByPath`  方法：

```typescript
import React from 'react'
import { matchPath } from 'react-router-dom'

export interface FC extends React.FC {
  getInitialProps?: (params: any) => Promise<any>
  Layout?: React.FC
}

export interface RouteItem {
  path: string
  exact?: boolean
  Component: () => FC
}

const NotFound: FC = () => {
  return (
    <div>路由查询404</div>
  )
}

const getComponentByPath = (routes: RouteItem[], path: string) => {
  // 根据请求的 path 查找对应的 component
  const matchRoute = routes.find(route => {
    // 找不到对应的组件时返回 NotFound 组件
  	return matchPath(path, route)) || { Component: () => NotFound }
  })

  // Notes:
  //  需要获取当前路由是否存在匹配的 Layout
  return {
      Component:  matchRoute.Component,
      Layout
   }
}

export default getComponentByPath
```

### 服务端渲染

根据路径获取到需要渲染的组件以及调用 `getInitialProps`  获取数据并渲染， 并在服务端编译为** HTML 返回给客户端。

#### 渲染入口

```jsx
// .ice/server.js
import React, { useState, useEffect } from 'react'
import { renderToString } from 'react-dom/server'
import * as ejs from 'ejs'
import routes from '@/routes'

const serverRender = async (ctx) => {
  // 01. 根据 ctx.path 获取请求的具体组件
  const { Component, Layout } = getComponentByPath(routes, ctx.path)
  
  // 02. 页面数据：判断是否有 getInitialProps 方法，如果有则调用 getInitialProps 方法获取数据
  const pageInitialData = Component.getInitialProps ? await Component.getInitialProps(ctx) : {}
  
  // 03. 将数据作为组件的 props 传入，使得组件可以通过 props.xxx 的方式来读取到服务端获取的数据
  const element = (
     <StaticRouter location={ctx.req.url} context={... pageInitialData}>
         <Layout  {...initialData}>
           <Component {...initialData} />
         </Layout>
    </StaticRouter>
  )

  // 04. 获取组件 HTML 内容
  const elementHtml = renderToString(element);
  
  // 05. 组装 HTML 内容
  const html = ejs.render(templateContent, {
    htmlContent,
    ...matchComponent
  });
  
  return html
}

export default serverRender
```

#### HTML 模板

```html
<html <% if(htmlAttrs){ %> <%- htmlAttrs %><% }%>>
  <head >
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge,chrome=1" />
    <meta name="viewport" content="width=device-width" />
    <% if(meta){ %> <%- meta %><% }%>
    <title><%- title %></title>
    <% if (link) { %>
    <%- link %>
    <%} else { %>
    <link href="<%- ASSET_PATH %>/css/index.css" rel="stylesheet">
    <% } %>
    <script>
       <!-- 注入数据 -->
       <% if (initialData) { %>
          window.__INITIAL_DATA__ = <%- initialData %>;
          window.__SSR__= true
       <% } %>
    </script>
  </head>

<body <% if(bodyAttrs){ %> <%- bodyAttrs %><% }%>>
  <div id="ice-container"></div>
  <% if (script) { %>
  <%- script %>
  <%} else { %>
  <script type="text/javascript" src="<%- ASSET_PATH %>/js/index.js"></script>
  <% } %>
</body>
</html>
```

### 客户端 hydrate

通过获取到服务端直出的 HTML 字符串，能够展现一个有内容的页面，但此时的页面并没有绑定事件和数据，需要通过 `React.hydrate` 进行处理。

```jsx
// build-plugin-ice-ssr/module.ts
import * as React from 'react';
import * as ReactDOM from 'react-dom';

const module = ({ modifyDOMRender, wrapperRouteComponent }) => {

  // 01. 包装路由组件当路由切换时调用 getInitialProps 方法
  wrapperRouteComponent(wrapperRouteComponentHoc)
  
  modifyDOMRender(({ App, appMountNode }) => {
    return new Promise(resolve => {
      // 02. 客户端渲染 | 兼容 hydrate 和 render
      ReactDOM[window.__SSR__ ? 'hydrate' : 'render'](<App />, appMountNode, resolve);
    })
  });
}

export default module;
```

<br />wrapperRouteComponentHoc 实现：

```typescript
function wrapperRouteComponentHoc(RouteComponent) {
  const WrapperRouteComponent = (props) => {
    const { staticContext } = props;
    // 通过 StaticRouter 提供的 staticContext 获取服务端渲染时透传的数据
    const { initialData } = staticContext;
    const [data, setData] = useState(initialData);

    useEffect(() => {
      // 服务端渲染直出的情况，客户端不再重复调用 getInitialProps
      if (window.__INIT_DATA__) {
        // 只有在首次进入页面需要将 window.__INITIAL_DATA__ 作为 props，路由切换时不需要重新请求
        // 使用后将服务端直出数据设置为空，否则其他页面会使用
        props = Object.assign({}, props,  window.__INITIAL_DATA__)
        window.__INIT_DATA__ = null
      } else {
        // 服务端没有直出数据，前端主动调用 getInitialProps
        if (RouteComponent.getInitialProps) {
          (async () => {
            const data = await RouteComponent.getInitialProps();
            setData(data);
          }());
        }
      }
    }, [])

    return <RouteComponent  {...props, ...data} />;
  }

  return WrapperRouteComponent;
}
```

### Store SSR
TODO

### 

## 讨论
  •  html template 模版 - 差异化内容在框架层面收敛（比如 pageConfig）
  •  渲染入口问题， createApp 同构，支持服务端 render
  •  server 构建需要考虑 externals 问题
  •  html 模版，分内置 html 和 SSR 两个场景
  •  initialProps 组件初始化问题，getInitialProps 执行是否阻塞问题，分应用级和路由级分情况看
  •  initialProps 逻辑不应该 plugin-store 中调用，其他地方也会消费这份数据
  •  createApp 流程重新梳理

* 区分 SEO 场景和性能
  - 性能场景：应用级别定义，比如支持服务端可以直接 DB 拿数据的逻辑
  - SEO 场景：路由级别定义

**Comment by imsobear** [comment]
## 使用说明

### 工程配置

在 build.json 配置 ssr 为 true

```diff
{
+ "ssr": true,
}
```

### 应用数据

```diff
import { createApp } from 'ice';
createApp({
  app: {
    // 获取初始数据
+   getInitialData: async () => {
+     return {};
+   }
  },
  store: {
    // 开发者自己决定 initialData 里的哪些数据作为 initialStates
+   getInitialStates: (initialData) => {
+     return initialData.states;
+   }
  }
});
```

### 应用数据使用

TODO：除了 initialStates，其他业务代码里如何使用 initialData

### 页面数据

> 有 SEO 诉求才需要，其他场景理论上不需要

> Page 级别 Model 的 initialStates 暂不支持通过 getInitialProps 获取

```diff
import React from 'react'
import { request } from 'ice'

const Home = ({ stars }) => {
  return <div>{stars}</div>
};

+Home.getInitialProps = async () => {
+  const res = await request('https://api.github.com/repos/ice-lab/icejs');
+  const json = await res.json();
+  return { stars: json.stargazers_count };
+};

export default Home;
```

### 构建产物

```
.
├── build
│   ├── index.html
│   ├── css/index.css
│   ├── js/index.js
│   └── server.js
```

## 实现方案

### 服务端调用

```js
router.get('/*', async (ctx) => {
  // const serverBundlePath = await downloadBundle('http://xxxx/server.js');
  const render = require(serverBundlePath);
  const html = await render({
    pathname: ctx.req.pathname,
    // 服务端可通过 db 等方式直接获取 initialData，否则调用前端声明的 app.getInitialData 获取
    initialData: {},
  });

  ctx.res.body = html;
});
```

### 构造 sever entry

`ice/server.js` 通过 plugin-ice-ssr/index.ts copy 到 ice 目录：

```js
// ice/server.js
import { matchPath } from 'ice';
import { createApp } from 'ice/createApp';
import routes from 'ice/routes';

// 服务端运行，构造一个假的 window
window = {};

export async function render({ pathname, initialData }) {
  // TODO: how to get appConfig.app.getInitialData
  const appConfig = {...};

  if (!initialData) {
    initialData = appConfig.app.getInitialData ? await appConfig.app.getInitialData() : {};
  }

  const PageComponent = getComponentByPath(pathname) || {};
  const pageInitialProps = PageComponent.getInitialProps ? await PageComponent.getInitialProps() : {};

  const renderedContent = await createApp(appConfig, { initialData, pageInitialProps, isServer: true });
  const htmlContent = ''; // build/index.html 内容
  const windowScripts = {
    __INIT_DATA__: {
      app: initialData,
      [pathname]: pageInitialProps
    },
    __SSR__: true,
  };

  return renderedContent + htmlContent + windowScripts;
};

function getComponentByPath(path: string) => {
  const matchRoute = routes.find(route => {
    // 找不到对应的组件时返回 NotFound 组件
    return matchPath(path, route));
  });

  return matchRoute.Component;
}

functon getHtmlContent() {
   return `<%= htmlContent %>`;
}
```

### createApp 增强

```js
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import ReactDOMServer from 'react-dom/server';
import RuntimeModule from './runtimeModule'

function createApp(customConfig: IAppConfig, { initialData, pageInitialData, isServer: false }) {
  const appConfig = deepmerge(defaultAppConfig, customConfig)

  if (isServer) {
    appConfig.router.type = 'static';
  } else {
    if (window.__INIT_DATA__) {
      initialData = window.__INIT_DATA__.app;
    } else {
      initialData = appConfig.app.getInitialData ? await appConfig.app.getInitialData() : {};
    }
  }

  // initialData, isServer 可以透传给插件 module
  const runtime = new RuntimeModule(appConfig, { initialData, isServer, pageInitialProps })
  runtime.loadModlues()

  return renderApp(runtime, isServer);
}

function renderApp(runtime, isServer) {
  // ...
  function App() {
    const appContent = (
      <AppRouter />
    );
    return AppProvider ? <AppProvider>{appContent}</AppProvider> : appContent;
  }

  if (isServer) {
    // server 不支持 modifyDOMRender 有没有问题
    return ReactDOMServer.renderToString(App);
  } else {
    if (modifyDOMRender) {
      return modifyDOMRender({ App, appMountNode })
    } else {
      return ReactDOM[window.__SSR__ ? 'hydrate' : 'render'](<App />, appMountNode);
    }
  }
}

export { createApp }
```

### plugin-router 包裹组件支持 getInitialProps

```js
import * as React from 'react';
import * as ReactDOM from 'react-dom';

export default const module = ({ modifyDOMRender, wrapperRouteComponent, isServer, pageInitialProps }) => {
  // 包装路由组件当路由切换时调用 getInitialProps 方法，这个逻辑是不是放在 plugin-router 里更好
  wrapperRouteComponent(wrapperRouteComponentHoc)
}

function wrapperRouteComponentHoc(RouteComponent) {
  const WrapperRouteComponent = (props) => {
    // TODO: matched 哪里来的，是不是要把 pathname 传进来，这里再 matchPath 下？
    if (isServer && matched) {
      // 在服务端渲染对应的页面组件
      return <RouteComponent {...props, ...pageInitialProps} />;
    }

    const [data, setData] = useState(window.__INIT_DATA__ ? window.__INIT_DATA__[pathname] : {});
    useEffect(() => {
      if (window.__INIT_DATA__ && window.__INIT_DATA__[pathname]) {
        // 前端切换回这个页面时不再使用服务端的初始数据
        window.__INIT_DATA__[pathname] = null;
      } else {
        // 服务端没有直出数据，前端主动调用 getInitialProps
        if (RouteComponent.getInitialProps) {
          (async () => {
            const data = await RouteComponent.getInitialProps();
            setData(data);
          }());
        }
      }
    }, [])

    return <RouteComponent  {...props, ...data} />;
  }

  return WrapperRouteComponent;
}
```

### Store SSR

plugin-store module.ts:

```js
import * as React from 'react'
import AppStore from '$ice/appModels'

export default ({ addProvider, wrapperRouteComponent, appConfig, initialData }) => {
  const { store = {} } = appConfig;

  const StoreProvider = ({children}) => {
    const initialStates = store.getInitialStates ? store.getInitialStates(initialData) : (store.initialStates || {});
    return (
      <AppStore.Provider initialStates={initialStates}>
        {children}
      </AppStore.Provider>
    )
  }

  if (AppStore) {
    addProvider(StoreProvider)
  }
}
```

**Comment by imsobear** [comment]
讨论点：

- 除了 initialStates 以外，其他业务代码中如何使用 initialData
- 通过 plugin-ssr index.ts 构造出来的 server.ts 怎么获取 appConfig
- server.ts 里怎么拿到构建出来的 html 内容
- plugin-router 包裹页面组件时，如果是服务端渲染并且 path 匹配的就是这个页面组件，那么直接把 pageInitialProps 传进去即可，不需要再包裹 useEffect，但是这个 case 怎么判断比较合理

**Comment by chenbin92** [comment]
### TODO

**开发调试环境**
- [x] 通过 registerTask 新增 server.js 的构建任务
- [x] 通过 devServer 在 before/after 阶段提供 SSR 服务
   - [x] 读取 server.js
  - [x] 调用 serverRender
  - [x] 根据 path 返回对应的 html

**新增 Server Entry**
> plugin-ssr/index.js
- [x] 获取 appConfig
- [x] 执行 appConfig.app.getInitialState 逻辑
- [x] 根据路由 path 匹配对应的组件并执行组件的 getInitialProps 逻辑 （getComponentByPath）
- [x] 调用 createApp 并传入 appConfig/initialData/pageInitialProps 返回 renderedContent
- [x] 通过 html-webpack-plugin 获取 html 并注入全局变量 
- [x] 最终返回 HTML 字符串 htmlStr = renderedContent + windowData

**createApp 支持 SSR**
- [x] SSR 模式
  - [x] 新增 StaticRouter 逻辑
  - [x] 调用 ReactDOMServer.renderToString();
- [x] CSR 模式
  - [x] 执行 appConfig.app.getInitialData 逻辑得到 initialData
- [x] 透传 initialData/pageInitialProps 等数据到 RuntimeModule
- [x] 根据是否是 SSR 调用 hydrate 还是 render

**plugin-router 支持 SSR**
- [x] 包装路由组件当路由切换时调用 getInitialProps 方法
- [x] 如果是 SSR 则返回匹配到的对应的组件
- [x] 如果是 CSR 则调用匹配到的组件的 getInitialProps 方案
- [x] 最终返回路由组件

**plugin-store 支持 SSR**
- [x] 通过 runtime module 获取 initialData 并透传给 store 的 getInitialStates 方法
- [x] 如果在 appConfig 中自定义了 getInitialStates 则调用或者使用 initialData 传递给 Provider

**Comment by chenbin92** [comment]
已发布 ice.js@1.1.0 版本支持 ssr
